# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # Audio Model.
  class Audio < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The media object ID. Required when you are not using a link.
    # @return [String]
    attr_accessor :id

    # The protocol and URL of the media to be sent. Use only with HTTP/HTTPS
    # URLs. Required when you are not using an uploaded media ID.
    # @return [String]
    attr_accessor :link

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['link'] = 'link'
      @_hash
    end

    # A mapping from model property names to types.
    def self.types
      @_types = {} if @_types.nil?
      @_types['id'] = 'String'
      @_types['link'] = 'String'
      @_types
    end

    # An array for optional fields
    def self.optionals
      %w[
        id
        link
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(id = nil,
                   link = nil)
      @id = id unless id == SKIP
      @link = link unless link == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      names.each do |key, value|
        has_default_value = false
        if !((hash.key? value) || (optionals.include? key)) && !has_default_value
          raise ArgumentError,
                "#{value} is not present in the provided hash"
        end
      end

      # Extract variables from the hash.
      id = hash.key?('id') ? hash['id'] : SKIP
      link = hash.key?('link') ? hash['link'] : SKIP

      # Create object from extracted values.
      Audio.new(id,
                link)
    end
  end
end
