# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # Document Model.
  class Document < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # It is the media object ID. Required when you are not using a link.
    # @return [String]
    attr_accessor :id

    # The protocol and URL of the media to be sent. Use only with HTTP/HTTPS
    # URLs. Required when you are not using an uploaded media ID.
    # @return [String]
    attr_accessor :link

    # Describes the specified document media.
    # @return [String]
    attr_accessor :caption

    # Describes the filename for the specific document.
    # @return [String]
    attr_accessor :filename

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['link'] = 'link'
      @_hash['caption'] = 'caption'
      @_hash['filename'] = 'filename'
      @_hash
    end

    # A mapping from model property names to types.
    def self.types
      @_types = {} if @_types.nil?
      @_types['id'] = 'String'
      @_types['link'] = 'String'
      @_types['caption'] = 'String'
      @_types['filename'] = 'String'
      @_types
    end

    # An array for optional fields
    def self.optionals
      %w[
        id
        link
        caption
        filename
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(id = nil,
                   link = nil,
                   caption = nil,
                   filename = nil)
      @id = id unless id == SKIP
      @link = link unless link == SKIP
      @caption = caption unless caption == SKIP
      @filename = filename unless filename == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      names.each do |key, value|
        has_default_value = false
        if !((hash.key? value) || (optionals.include? key)) && !has_default_value
          raise ArgumentError,
                "#{value} is not present in the provided hash"
        end
      end

      # Extract variables from the hash.
      id = hash.key?('id') ? hash['id'] : SKIP
      link = hash.key?('link') ? hash['link'] : SKIP
      caption = hash.key?('caption') ? hash['caption'] : SKIP
      filename = hash.key?('filename') ? hash['filename'] : SKIP

      # Create object from extracted values.
      Document.new(id,
                   link,
                   caption,
                   filename)
    end
  end
end
