# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # Location Model.
  class Location < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Latitude of the location.
    # @return [String]
    attr_accessor :latitude

    # Longitude of the location.
    # @return [String]
    attr_accessor :longitude

    # Name of the location.
    # @return [String]
    attr_accessor :name

    # Address of the location. Only displayed if name is present.
    # @return [String]
    attr_accessor :address

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['latitude'] = 'latitude'
      @_hash['longitude'] = 'longitude'
      @_hash['name'] = 'name'
      @_hash['address'] = 'address'
      @_hash
    end

    # A mapping from model property names to types.
    def self.types
      @_types = {} if @_types.nil?
      @_types['latitude'] = 'String'
      @_types['longitude'] = 'String'
      @_types['name'] = 'String'
      @_types['address'] = 'String'
      @_types
    end

    # An array for optional fields
    def self.optionals
      %w[
        name
        address
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(latitude = nil,
                   longitude = nil,
                   name = nil,
                   address = nil)
      @latitude = latitude unless latitude == SKIP
      @longitude = longitude unless longitude == SKIP
      @name = name unless name == SKIP
      @address = address unless address == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      names.each do |key, value|
        has_default_value = false
        if !((hash.key? value) || (optionals.include? key)) && !has_default_value
          raise ArgumentError,
                "#{value} is not present in the provided hash"
        end
      end

      # Extract variables from the hash.
      latitude = hash.key?('latitude') ? hash['latitude'] : SKIP
      longitude = hash.key?('longitude') ? hash['longitude'] : SKIP
      name = hash.key?('name') ? hash['name'] : SKIP
      address = hash.key?('address') ? hash['address'] : SKIP

      # Create object from extracted values.
      Location.new(latitude,
                   longitude,
                   name,
                   address)
    end
  end
end
