# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # ResponseContact Model.
  class ResponseContact < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :input

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :wa_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['input'] = 'input'
      @_hash['wa_id'] = 'wa_id'
      @_hash
    end

    # A mapping from model property names to types.
    def self.types
      @_types = {} if @_types.nil?
      @_types['input'] = 'String'
      @_types['wa_id'] = 'String'
      @_types
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(input = nil,
                   wa_id = nil)
      @input = input unless input == SKIP
      @wa_id = wa_id unless wa_id == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      names.each do |key, value|
        has_default_value = false
        if !((hash.key? value) || (optionals.include? key)) && !has_default_value
          raise ArgumentError,
                "#{value} is not present in the provided hash"
        end
      end

      # Extract variables from the hash.
      input = hash.key?('input') ? hash['input'] : SKIP
      wa_id = hash.key?('wa_id') ? hash['wa_id'] : SKIP

      # Create object from extracted values.
      ResponseContact.new(input,
                          wa_id)
    end
  end
end
